name: Push Migrations
on:
  # Run whenever code is changed in the master branch,
  # change this to your root branch.
  push:
    branches:
      - main
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN }}
      - uses: ariga/atlas-action/migrate/push@v1
        with:
          dir: 'file://migrations'
          dir-name: 'clicker_db'
          dev-url: postgres://postgres:admin@localhost:5432/clicker_db?sslmode=disable