name: Atlas
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci-atlas.yaml
      - 'db/migration/*'
  pull_request:
    paths:
      - 'db/migration/*'
# Permissions to write comments on the pull request.
permissions:
  contents: read
  pull-requests: write
jobs:
  atlas:
    services:
      # Spin up a postgres:15 container to be used as the dev-database for analysis.
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: clicker_db
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN_RX3B70 }}
      - uses: ariga/atlas-action/migrate/lint@v1
        with:
          dir: 'file://migration'
          dir-name: 'clicker_db'
          dev-url: 'postgres://postgres:admin@localhost:5432/clicker_db?sslmode=disable'
      - uses: ariga/atlas-action/migrate/push@v1
        if: github.ref == 'refs/heads/main'
        with:
          dir: 'file://migration'
          dir-name: 'clicker_db'
          dev-url: 'postgres://postgres:admin@localhost:5432/clicker_db?sslmode=disable'